server:
  port: 15001

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@www.senhu.com:10001/eureka/
  instance:
    prefer-ip-address: true   #注册服务时使用ip而非计算机名


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  application:
    name: turzine-stream
