server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 10009
  max-http-header-size: 4048576

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@118.24.38.46:10001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: config-server
  data:
    mongodb:
      host: 118.24.38.46
      port: 27017
      database: config_repos
      username: senhu
      password: 521428Slyt
  profiles:
    active: mongodb
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh,info,health
  endpoint:
    health:
      show-details: always