server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 10009
  max-http-header-size: 4048576

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@118.24.38.46:10001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ssaw-config
  data:
    mongodb:
      host: 118.24.38.46
      port: 27017
      database: config_repos
      username: senhu
      password: 521428Slyt
  profiles:
    active: mongodb
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428

ssaw:
  resource:
    code: 3
    resource-id: 配置中心
    description: 配置中心
    self: true
    icon: el-icon-setting
    system-white-list: /actuator/**,/app-**
    white-list: /actuator/**,/app-**

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh,info,health
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true                                         #默认为true 为true时hystrix的超时时间控制熔断， 为false时ribbon的超时时间控制熔断。
        isolation:
          strategy: THREAD                                      #隔离策略 默认线程隔离策略 可设置为信号量隔离策略
          thread:
            timeoutInMilliseconds: 12000                        #断路器超时时间，默认1000ms 要使这个生效 必须配置ribbon.ReadTimeout

feign:
  hystrix:
    enabled: true

ribbon:                                                         #Ribbo处理超时配置
  ReadTimeout: 10000
  ConnectTimeout: 3000
  eager-load:
    enabled: true